<?php if ($this->user): ?>
    <form method="post" action="addPersonas">
    <div class="mb-3">
        <label for="Nombre" class="form-label">Nombre:</label>
        <input name="Nombre" type="text" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="edad" class="form-label">Edad:</label>
        <input name="edad" type="number" step="0.01" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="Cantidad" class="form-label">Cantidad de pasajes:</label>
        <input name="Cantidad" type="number" class="form-control" required>
    </div>
    //hasta aca cambie //
    <div class="mb-3">
        <label for="id_aerolinea" class="form-label">Aerolinea:</label>
        <select name="id_aerolinea" class="form-control" required>
            <option value="" disabled selected>Seleccione una aerolinea</option>
            <?php foreach ($aerolineas as $aerolinea): ?>
                <option value="<?= $aerolinea->id; ?>"><?= $aerolinea->nombre; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Agregar Persona</button>
</form>
<?php endif; ?>