<ul class="list-group">
        <?php if(isset($aerolineas)): ?>
            <?php foreach($aerolineas as $aerolinea): ?>
                <li class="list-group-item item-aerolinea d-flex justify-content-between align-items-center">
                    <span>
                        <?=$aerolinea->Nombre; ?>
                    </span>
                    <span>
                        <a href="detallesaerolinea/<?=$aerolinea->id;?>" class="btn btn-success btn-sm text-white">Ver más</a>
                    </span>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
    
    <?php if($this->user): ?> 
        <div class="text-center mt-3">
            <a href="showAddAerolinea/" class="btn btn-primary">Hacer cambios</a>
        </div>
        <?php endif; ?>