<?php require './templates/layouts/header.phtml'; ?>

<?php if ($error): ?>
    <div class="alert alert-danger" role="alert">
    <?= $error ?>
    </div>
<?php endif ?>

<form method="post" action='login'>
    <div class="form-group">
        <label for="user">User:</label>
        <input type="text" class="form-control" id="user" name="user" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" required>
        <br>
    </div>
    <button type="submit" class="btn btn-primary">LogIn</button>
</form>
    
<?php require './templates/layouts/footer.phtml'; ?>