<?php require './templates/layouts/header.phtml'; ?>

<?php require './templates/add_personas.phtml'; ?>

<br>

<ul class="list-group">
    <?php if (isset($personas)): ?>
        <?php foreach ($personas as $persona): ?> 
            <li class="list-group-item item-aerolinea d-flex justify-content-between align-items-center">
                <span>
                    <b><?= $persona->Nombre; ?></b> 
                </span>
                <span class="actions">
                    <button type="button" class="btn btn-success btn-sm">
                        <a href="detallespersona/<?= $persona->id_persona; ?>" class="text-white">Ver más</a>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ml-2">
                        <a href="deleteModel/<?= $persona->id_persona; ?>" class="text-white">Eliminar</a>
                    </button>
                    <button type="button" class="btn btn-warning btn-sm ml-2">
                        <a href="showEditModelo/<?= $persona->id_persona; ?>" class="text-white">Editar</a>
                    </button>
                </span>
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li class="list-group-item">No hay personas disponibles.</li>
    <?php endif; ?>
</ul>

<?php require './templates/layouts/footer.phtml'; ?>